hub:
  image: selenium/hub
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox-debug
  links:
    - hub
  ports:
    - "5902:5900"
chrome:
  image: selenium/node-chrome-debug
  links:
    - hub
  ports:
    - "5901:5900"
tests:
  image: selenium/standalone-chrome
  links:
    - hub
  volumes:
    - /home/ubuntu/tests:/var/tmp